# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

install: 
  - pip install -r requirements.txt --use-mirrors
  #- python setup.py install

before_script:
  - pip install -r test_requirements.txt --use-mirrors

script: 
  #- py.test --pep8 mwclient -v --doctest-modules tests/client-test.py
  - py.test -v --doctest-modules tests/client-test.py
